# Statistical Inference

통계적 추론은 데이터에 기초하여 모집단의 모수에 관한 예측을 추정과 불확실성을 포함한 진술의 형태로 구성하는 것이다. 즉, 데이터가 현실 속에서 우리가 연구하고자 하는 모집단에 대한 하나의 표본이라고 할 때, 그 표본을 통해 모집단에서 존재하는 관계양상 등(모수)에 관해 예측하고, 그 예측에는 표본-모집단의 관계로 인한 불확실성이 존재하기에 그것 또한 반영하여 진술(statement)의 형태로 가공해내는 것이다.

이 챕터에서는 확률모델, 추정(estimation), 편향(bias), 분산, 그리고 통계적 추론의 해석과 통계적 오차에 관한 기본적인 내용들을 다룬다. 나아가 통계적 추론에서 불확실성의 개념이 어떻게 연계되는지를 살펴보고 잡음이 있는 데이터(불확실성을 포함한 데이터)로부터 확실성을 이끌어내기 위해 가설 검정과 통계적 유의성을 사용하는 것의 문제 또한 짚어본다.

## Sampling distributions and generative models

### Sampling, measurement error, and model error

### The sampling distribution

## Estimates, standard errors, and confidence intervals

### Parameters, estimands, and estimates

### Standard errors, inferential uncertainty, and confidence intervals

### Standard errors and confidence intervals for average and proportions

### Standard error and confidence interval for a proportion when $y = 0$ or $y = n$

### Standard error for a comparison

### Sampling distribution of the sample mean and standard deviation; normal and $\chi^2$ distributions

### Degrees of freedom

### Confidence intervals from the $t$ distribution

### Inference for discrete data

### Linear transformations

### Comparisons, visual and numerical

### Weighted averages

## Bias and unmodeled uncertainty

### Bias in estimation

### Adjusting inferences to account for bias and unmodeled uncertainty

## Statistical significance, hypothesis testing, and statistical errors

### Statistical significance

### Hypothesis testing for simple comparisons

#### Estimate, standard error, and degrees of freedom

#### Null and alternative hypotheses

### Hypothesis testing: general formulation

### Comparisons of parameters to fixed values and each other: interpreting confidence intervals as hypothesis tests

### Type 1 and type 2 errors and why we don’t like talking about them

### Type M (magnitude) and type S (sign) errors

### Hypothesis testing and statistical practice

## Problems with the concept of statistical significance

### Statistical significance is not the same as practical importance

### Non-significance is not the same as zero

### The difference between “significant” and “not significant” is not itself statistically significant

### Researcher degrees of freedom, $p$-hacking, and forking paths

### The statistical significance filter

### Example: A flawed study of ovulation and political attitudes

## Example of hypothesis testing: 55,000 residents need your help!

## Moving beyond hypothesis testing






