<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Background on regression modeling | Reading Notes for Regression and Other Stories</title>
  <meta name="description" content="Chapter 6 Background on regression modeling | Reading Notes for Regression and Other Stories" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Background on regression modeling | Reading Notes for Regression and Other Stories" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="pherephobia/regression_hgv" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Background on regression modeling | Reading Notes for Regression and Other Stories" />
  
  
  

<meta name="author" content="Sanghoon Park" />


<meta name="date" content="2021-06-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="simulation.html"/>
<link rel="next" href="simulation-1.html"/>
<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script async defer src="https://hypothes.is/embed.js"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88838732-1', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">GHV</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Overview</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#the-three-challenges-of-statistics"><i class="fa fa-check"></i><b>1.1</b> The three challenges of statistics</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#why-learn-regression"><i class="fa fa-check"></i><b>1.2</b> Why learn regression?</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#some-examples-of-regression"><i class="fa fa-check"></i><b>1.3</b> Some examples of regression</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#a-randomized-experiment-on-the-effect-of-an-educational-television-program"><i class="fa fa-check"></i><b>1.3.1</b> A randomized experiment on the effect of an educational television program</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#comparing-the-peacekeeping-and-gun-control-studies"><i class="fa fa-check"></i><b>1.3.2</b> Comparing the peacekeeping and gun-control studies</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#challenges-in-building-understanding-and-interpreting-regressions"><i class="fa fa-check"></i><b>1.4</b> Challenges in building, understanding, and interpreting regressions</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#regression-to-estimate-a-relationship-of-interest"><i class="fa fa-check"></i><b>1.4.1</b> Regression to estimate a relationship of interest</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#regression-to-adjust-for-differences-between-treatment-and-control-groups"><i class="fa fa-check"></i><b>1.4.2</b> Regression to adjust for differences between treatment and control groups</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#interpreting-coefficients-in-a-predictive-model"><i class="fa fa-check"></i><b>1.4.3</b> Interpreting coefficients in a predictive model</a></li>
<li class="chapter" data-level="1.4.4" data-path="index.html"><a href="index.html#building-interpreting-and-checking-regression-models"><i class="fa fa-check"></i><b>1.4.4</b> Building, interpreting, and checking regression models</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#classical-and-bayesian-inference"><i class="fa fa-check"></i><b>1.5</b> Classical and Bayesian inference</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#information"><i class="fa fa-check"></i><b>1.5.1</b> Information</a></li>
<li class="chapter" data-level="1.5.2" data-path="index.html"><a href="index.html#assumptions"><i class="fa fa-check"></i><b>1.5.2</b> Assumptions</a></li>
<li class="chapter" data-level="1.5.3" data-path="index.html"><a href="index.html#classical-inference"><i class="fa fa-check"></i><b>1.5.3</b> Classical inference</a></li>
<li class="chapter" data-level="1.5.4" data-path="index.html"><a href="index.html#bayesian-inference"><i class="fa fa-check"></i><b>1.5.4</b> Bayesian inference</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#computing-least-squares-and-bayesian-regression"><i class="fa fa-check"></i><b>1.6</b> Computing least squares and Bayesian regression</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-and-measurement.html"><a href="data-and-measurement.html"><i class="fa fa-check"></i><b>2</b> Data and Measurement</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-and-measurement.html"><a href="data-and-measurement.html#examining-where-data-come-from"><i class="fa fa-check"></i><b>2.1</b> Examining where data come from</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="data-and-measurement.html"><a href="data-and-measurement.html#details-of-measurement-can-be-important"><i class="fa fa-check"></i><b>2.1.1</b> Details of measurement can be important</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-and-measurement.html"><a href="data-and-measurement.html#validity-and-reliability"><i class="fa fa-check"></i><b>2.2</b> Validity and reliability</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="data-and-measurement.html"><a href="data-and-measurement.html#validity"><i class="fa fa-check"></i><b>2.2.1</b> Validity</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-and-measurement.html"><a href="data-and-measurement.html#reliability"><i class="fa fa-check"></i><b>2.2.2</b> Reliability</a></li>
<li class="chapter" data-level="2.2.3" data-path="data-and-measurement.html"><a href="data-and-measurement.html#sample-selection"><i class="fa fa-check"></i><b>2.2.3</b> Sample selection</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-and-measurement.html"><a href="data-and-measurement.html#all-graphs-are-comparisons"><i class="fa fa-check"></i><b>2.3</b> All graphs are comparisons</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data-and-measurement.html"><a href="data-and-measurement.html#simple-scatterplots"><i class="fa fa-check"></i><b>2.3.1</b> Simple scatterplots</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-and-measurement.html"><a href="data-and-measurement.html#displaying-more-information-on-a-graph"><i class="fa fa-check"></i><b>2.3.2</b> Displaying more information on a graph</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-and-measurement.html"><a href="data-and-measurement.html#multiple-plots"><i class="fa fa-check"></i><b>2.3.3</b> Multiple plots</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-and-measurement.html"><a href="data-and-measurement.html#grids-of-plots"><i class="fa fa-check"></i><b>2.3.4</b> Grids of plots</a></li>
<li class="chapter" data-level="2.3.5" data-path="data-and-measurement.html"><a href="data-and-measurement.html#applying-graphical-principles-to-numerical-displays-and-communication-more-generally"><i class="fa fa-check"></i><b>2.3.5</b> Applying graphical principles to numerical displays and communication more generally</a></li>
<li class="chapter" data-level="2.3.6" data-path="data-and-measurement.html"><a href="data-and-measurement.html#graphics-for-understanding-statistical-models"><i class="fa fa-check"></i><b>2.3.6</b> Graphics for understanding statistical models</a></li>
<li class="chapter" data-level="2.3.7" data-path="data-and-measurement.html"><a href="data-and-measurement.html#graphs-as-comparisons"><i class="fa fa-check"></i><b>2.3.7</b> Graphs as comparisons</a></li>
<li class="chapter" data-level="2.3.8" data-path="data-and-measurement.html"><a href="data-and-measurement.html#graphs-of-fitted-models"><i class="fa fa-check"></i><b>2.3.8</b> Graphs of fitted models</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-and-measurement.html"><a href="data-and-measurement.html#data-and-adjustment-trends-in-mortality-rates"><i class="fa fa-check"></i><b>2.4</b> Data and adjustment: trends in mortality rates</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html"><i class="fa fa-check"></i><b>3</b> Some Basic Methods in Mathematics and Probability</a>
<ul>
<li class="chapter" data-level="3.1" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#weighted-averages"><i class="fa fa-check"></i><b>3.1</b> Weighted averages</a></li>
<li class="chapter" data-level="3.2" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#vectors-and-matrices"><i class="fa fa-check"></i><b>3.2</b> Vectors and matrices</a></li>
<li class="chapter" data-level="3.3" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#graphing-a-line"><i class="fa fa-check"></i><b>3.3</b> Graphing a line</a></li>
<li class="chapter" data-level="3.4" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#exponential-and-power-law-growth-and-decline-logarithmic-and-log-log-relationships"><i class="fa fa-check"></i><b>3.4</b> Exponential and power-law growth and decline; logarithmic and log-log relationships</a></li>
<li class="chapter" data-level="3.5" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#probability-distributions"><i class="fa fa-check"></i><b>3.5</b> Probability distributions</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#mean-and-standard-deviation-of-a-probability-distribution"><i class="fa fa-check"></i><b>3.5.1</b> Mean and standard deviation of a probability distribution</a></li>
<li class="chapter" data-level="3.5.2" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#normal-distribution-mean-and-standard-deviation"><i class="fa fa-check"></i><b>3.5.2</b> Normal distribution; mean and standard deviation</a></li>
<li class="chapter" data-level="3.5.3" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#linear-transformations"><i class="fa fa-check"></i><b>3.5.3</b> Linear transformations</a></li>
<li class="chapter" data-level="3.5.4" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#mean-and-standard-deviation-of-the-sum-of-correlated-random-variables"><i class="fa fa-check"></i><b>3.5.4</b> Mean and standard deviation of the sum of correlated random variables</a></li>
<li class="chapter" data-level="3.5.5" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#lognormal-distribution"><i class="fa fa-check"></i><b>3.5.5</b> Lognormal distribution</a></li>
<li class="chapter" data-level="3.5.6" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#binomial-distribution"><i class="fa fa-check"></i><b>3.5.6</b> Binomial distribution</a></li>
<li class="chapter" data-level="3.5.7" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#poisson-distribution"><i class="fa fa-check"></i><b>3.5.7</b> Poisson distribution</a></li>
<li class="chapter" data-level="3.5.8" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#unclassified-probability-distribution"><i class="fa fa-check"></i><b>3.5.8</b> Unclassified probability distribution</a></li>
<li class="chapter" data-level="3.5.9" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#probability-distributions-for-error"><i class="fa fa-check"></i><b>3.5.9</b> Probability distributions for error</a></li>
<li class="chapter" data-level="3.5.10" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#comparing-distributions"><i class="fa fa-check"></i><b>3.5.10</b> Comparing distributions</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#probability-modeling"><i class="fa fa-check"></i><b>3.6</b> Probability modeling</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#using-an-empirical-forecast"><i class="fa fa-check"></i><b>3.6.1</b> Using an empirical forecast</a></li>
<li class="chapter" data-level="3.6.2" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#using-an-reasonable-seeming-but-inappropriate-probability-model"><i class="fa fa-check"></i><b>3.6.2</b> Using an reasonable-seeming but inappropriate probability model</a></li>
<li class="chapter" data-level="3.6.3" data-path="some-basic-methods-in-mathematics-and-probability.html"><a href="some-basic-methods-in-mathematics-and-probability.html#general-lessons-for-probability-modeling"><i class="fa fa-check"></i><b>3.6.3</b> General lessons for probability modeling</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>4</b> Statistical Inference</a>
<ul>
<li class="chapter" data-level="4.1" data-path="statistical-inference.html"><a href="statistical-inference.html#sampling-distributions-and-generative-models"><i class="fa fa-check"></i><b>4.1</b> Sampling distributions and generative models</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="statistical-inference.html"><a href="statistical-inference.html#sampling-measurement-error-and-model-error"><i class="fa fa-check"></i><b>4.1.1</b> Sampling, measurement error, and model error</a></li>
<li class="chapter" data-level="4.1.2" data-path="statistical-inference.html"><a href="statistical-inference.html#the-sampling-distribution"><i class="fa fa-check"></i><b>4.1.2</b> The sampling distribution</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="statistical-inference.html"><a href="statistical-inference.html#estimates-standard-errors-and-confidence-intervals"><i class="fa fa-check"></i><b>4.2</b> Estimates, standard errors, and confidence intervals</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="statistical-inference.html"><a href="statistical-inference.html#parameters-estimands-and-estimates"><i class="fa fa-check"></i><b>4.2.1</b> Parameters, estimands, and estimates</a></li>
<li class="chapter" data-level="4.2.2" data-path="statistical-inference.html"><a href="statistical-inference.html#standard-errors-inferential-uncertainty-and-confidence-intervals"><i class="fa fa-check"></i><b>4.2.2</b> Standard errors, inferential uncertainty, and confidence intervals</a></li>
<li class="chapter" data-level="4.2.3" data-path="statistical-inference.html"><a href="statistical-inference.html#standard-errors-and-confidence-intervals-for-average-and-proportions"><i class="fa fa-check"></i><b>4.2.3</b> Standard errors and confidence intervals for average and proportions</a></li>
<li class="chapter" data-level="4.2.4" data-path="statistical-inference.html"><a href="statistical-inference.html#standard-error-and-confidence-interval-for-a-proportion-when-y-0-or-y-n"><i class="fa fa-check"></i><b>4.2.4</b> Standard error and confidence interval for a proportion when <span class="math inline">\(y = 0\)</span> or <span class="math inline">\(y = n\)</span></a></li>
<li class="chapter" data-level="4.2.5" data-path="statistical-inference.html"><a href="statistical-inference.html#standard-error-for-a-comparison"><i class="fa fa-check"></i><b>4.2.5</b> Standard error for a comparison</a></li>
<li class="chapter" data-level="4.2.6" data-path="statistical-inference.html"><a href="statistical-inference.html#sampling-distribution-of-the-sample-mean-and-standard-deviation-normal-and-chi2-distributions"><i class="fa fa-check"></i><b>4.2.6</b> Sampling distribution of the sample mean and standard deviation; normal and <span class="math inline">\(\chi^2\)</span> distributions</a></li>
<li class="chapter" data-level="4.2.7" data-path="statistical-inference.html"><a href="statistical-inference.html#degrees-of-freedom"><i class="fa fa-check"></i><b>4.2.7</b> Degrees of freedom</a></li>
<li class="chapter" data-level="4.2.8" data-path="statistical-inference.html"><a href="statistical-inference.html#confidence-intervals-from-the-t-distribution"><i class="fa fa-check"></i><b>4.2.8</b> Confidence intervals from the <span class="math inline">\(t\)</span> distribution</a></li>
<li class="chapter" data-level="4.2.9" data-path="statistical-inference.html"><a href="statistical-inference.html#inference-for-discrete-data"><i class="fa fa-check"></i><b>4.2.9</b> Inference for discrete data</a></li>
<li class="chapter" data-level="4.2.10" data-path="statistical-inference.html"><a href="statistical-inference.html#linear-transformations-1"><i class="fa fa-check"></i><b>4.2.10</b> Linear transformations</a></li>
<li class="chapter" data-level="4.2.11" data-path="statistical-inference.html"><a href="statistical-inference.html#comparisons-visual-and-numerical"><i class="fa fa-check"></i><b>4.2.11</b> Comparisons, visual and numerical</a></li>
<li class="chapter" data-level="4.2.12" data-path="statistical-inference.html"><a href="statistical-inference.html#weighted-averages-1"><i class="fa fa-check"></i><b>4.2.12</b> Weighted averages</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="statistical-inference.html"><a href="statistical-inference.html#bias-and-unmodeled-uncertainty"><i class="fa fa-check"></i><b>4.3</b> Bias and unmodeled uncertainty</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="statistical-inference.html"><a href="statistical-inference.html#bias-in-estimation"><i class="fa fa-check"></i><b>4.3.1</b> Bias in estimation</a></li>
<li class="chapter" data-level="4.3.2" data-path="statistical-inference.html"><a href="statistical-inference.html#adjusting-inferences-to-account-for-bias-and-unmodeled-uncertainty"><i class="fa fa-check"></i><b>4.3.2</b> Adjusting inferences to account for bias and unmodeled uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="statistical-inference.html"><a href="statistical-inference.html#statistical-significance-hypothesis-testing-and-statistical-errors"><i class="fa fa-check"></i><b>4.4</b> Statistical significance, hypothesis testing, and statistical errors</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="statistical-inference.html"><a href="statistical-inference.html#statistical-significance"><i class="fa fa-check"></i><b>4.4.1</b> Statistical significance</a></li>
<li class="chapter" data-level="4.4.2" data-path="statistical-inference.html"><a href="statistical-inference.html#hypothesis-testing-for-simple-comparisons."><i class="fa fa-check"></i><b>4.4.2</b> Hypothesis testing for simple comparisons.</a></li>
<li class="chapter" data-level="4.4.3" data-path="statistical-inference.html"><a href="statistical-inference.html#hypothesis-testing-general-formulation."><i class="fa fa-check"></i><b>4.4.3</b> Hypothesis testing: general formulation.</a></li>
<li class="chapter" data-level="4.4.4" data-path="statistical-inference.html"><a href="statistical-inference.html#comparisons-of-parameters-to-fixed-values-and-each-other-interpreting-confidence-intervals-as-hypothesis-tests."><i class="fa fa-check"></i><b>4.4.4</b> Comparisons of parameters to fixed values and each other: interpreting confidence intervals as hypothesis tests.</a></li>
<li class="chapter" data-level="4.4.5" data-path="statistical-inference.html"><a href="statistical-inference.html#type-1-and-type-2-errors-and-why-we-dont-like-talking-about-them."><i class="fa fa-check"></i><b>4.4.5</b> Type 1 and type 2 errors and why we don’t like talking about them.</a></li>
<li class="chapter" data-level="4.4.6" data-path="statistical-inference.html"><a href="statistical-inference.html#type-m-magnitude-and-type-s-sign-errors."><i class="fa fa-check"></i><b>4.4.6</b> 4.4.6 Type M (magnitude) and type S (sign) errors.</a></li>
<li class="chapter" data-level="4.4.7" data-path="statistical-inference.html"><a href="statistical-inference.html#hypothesis-testing-and-statistical-practice."><i class="fa fa-check"></i><b>4.4.7</b> Hypothesis testing and statistical practice.</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="statistical-inference.html"><a href="statistical-inference.html#problems-with-the-concept-of-statistical-significance"><i class="fa fa-check"></i><b>4.5</b> Problems with the concept of statistical significance</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="statistical-inference.html"><a href="statistical-inference.html#statistical-significance-is-not-the-same-as-practical-importance."><i class="fa fa-check"></i><b>4.5.1</b> Statistical significance is not the same as practical importance.</a></li>
<li class="chapter" data-level="4.5.2" data-path="statistical-inference.html"><a href="statistical-inference.html#non-significance-is-not-the-same-as-zero."><i class="fa fa-check"></i><b>4.5.2</b> Non-significance is not the same as zero.</a></li>
<li class="chapter" data-level="4.5.3" data-path="statistical-inference.html"><a href="statistical-inference.html#the-difference-between-significant-and-not-significant-is-not-itself-statistically-significant."><i class="fa fa-check"></i><b>4.5.3</b> The difference between “significant” and “not significant” is not itself statistically significant.</a></li>
<li class="chapter" data-level="4.5.4" data-path="statistical-inference.html"><a href="statistical-inference.html#researcher-degrees-of-freedom-p-hacking-and-forking-paths."><i class="fa fa-check"></i><b>4.5.4</b> Researcher degrees of freedom, <span class="math inline">\(p\)</span>-hacking, and forking paths.</a></li>
<li class="chapter" data-level="4.5.5" data-path="statistical-inference.html"><a href="statistical-inference.html#the-statistical-significance-filter."><i class="fa fa-check"></i><b>4.5.5</b> The statistical significance filter.</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="statistical-inference.html"><a href="statistical-inference.html#moving-beyond-hypothesis-testing"><i class="fa fa-check"></i><b>4.6</b> Moving beyond hypothesis testing</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="simulation.html"><a href="simulation.html"><i class="fa fa-check"></i><b>5</b> Simulation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="simulation.html"><a href="simulation.html#simulation-of-discrete-probability-models"><i class="fa fa-check"></i><b>5.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="simulation.html"><a href="simulation.html#how-many-girls-in-400-births"><i class="fa fa-check"></i><b>5.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="5.1.2" data-path="simulation.html"><a href="simulation.html#accounting-for-twins"><i class="fa fa-check"></i><b>5.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="simulation.html"><a href="simulation.html#simulation-of-continuous-and-mixed-discretecontinuous-models"><i class="fa fa-check"></i><b>5.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="simulation.html"><a href="simulation.html#simulation-in-r-using-custom-made-functions"><i class="fa fa-check"></i><b>5.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="simulation.html"><a href="simulation.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation"><i class="fa fa-check"></i><b>5.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="5.4" data-path="simulation.html"><a href="simulation.html#bootstrapping-to-simulate-a-sampling-distribution"><i class="fa fa-check"></i><b>5.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="simulation.html"><a href="simulation.html#choices-in-defining-the-bootstrap-distribution"><i class="fa fa-check"></i><b>5.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="5.4.2" data-path="simulation.html"><a href="simulation.html#limitations-of-bootstrapping"><i class="fa fa-check"></i><b>5.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="simulation.html"><a href="simulation.html#fake-data-simulation-as-a-way-of-life"><i class="fa fa-check"></i><b>5.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html"><i class="fa fa-check"></i><b>6</b> Background on regression modeling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#regression-models"><i class="fa fa-check"></i><b>6.1</b> Regression models</a></li>
<li class="chapter" data-level="6.2" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#fitting-a-simple-regression-to-fake-data"><i class="fa fa-check"></i><b>6.2</b> Fitting a simple regression to fake data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#fitting-a-regression-and-displaying-the-results"><i class="fa fa-check"></i><b>6.2.1</b> Fitting a regression and displaying the results</a></li>
<li class="chapter" data-level="6.2.2" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#comparing-estimates-to-assumed-parameter-values"><i class="fa fa-check"></i><b>6.2.2</b> Comparing estimates to assumed parameter values</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#interpret-coefficients-as-comparisons-not-effects"><i class="fa fa-check"></i><b>6.3</b> Interpret coefficients as comparisons, not effects</a></li>
<li class="chapter" data-level="6.4" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#historical-origins-of-regression"><i class="fa fa-check"></i><b>6.4</b> Historical origins of regression</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#daughters-heights-regressing-to-the-mean"><i class="fa fa-check"></i><b>6.4.1</b> Daughters’ heights “regressing” to the mean</a></li>
<li class="chapter" data-level="6.4.2" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#fitting-the-model-in-r"><i class="fa fa-check"></i><b>6.4.2</b> Fitting the model in R</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#the-paradox-of-regression-to-the-mean"><i class="fa fa-check"></i><b>6.5</b> The paradox of regression to the mean</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#how-regression-to-the-mean-can-confuse-people-about-causal-inference-demonstration-using-fake-data"><i class="fa fa-check"></i><b>6.5.1</b> How regression to the mean can confuse people about causal inference; demonstration using fake data</a></li>
<li class="chapter" data-level="6.5.2" data-path="background-on-regression-modeling.html"><a href="background-on-regression-modeling.html#relation-of-regression-to-the-mean-to-the-larger-themes-of-the-book"><i class="fa fa-check"></i><b>6.5.2</b> Relation of “regression to the mean” to the larger themes of the book</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="simulation-1.html"><a href="simulation-1.html"><i class="fa fa-check"></i><b>7</b> Simulation</a>
<ul>
<li class="chapter" data-level="7.1" data-path="simulation-1.html"><a href="simulation-1.html#simulation-of-discrete-probability-models-1"><i class="fa fa-check"></i><b>7.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="simulation-1.html"><a href="simulation-1.html#how-many-girls-in-400-births-1"><i class="fa fa-check"></i><b>7.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="7.1.2" data-path="simulation-1.html"><a href="simulation-1.html#accounting-for-twins-1"><i class="fa fa-check"></i><b>7.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="simulation-1.html"><a href="simulation-1.html#simulation-of-continuous-and-mixed-discretecontinuous-models-1"><i class="fa fa-check"></i><b>7.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="simulation-1.html"><a href="simulation-1.html#simulation-in-r-using-custom-made-functions-1"><i class="fa fa-check"></i><b>7.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="simulation-1.html"><a href="simulation-1.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-1"><i class="fa fa-check"></i><b>7.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="7.4" data-path="simulation-1.html"><a href="simulation-1.html#bootstrapping-to-simulate-a-sampling-distribution-1"><i class="fa fa-check"></i><b>7.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="simulation-1.html"><a href="simulation-1.html#choices-in-defining-the-bootstrap-distribution-1"><i class="fa fa-check"></i><b>7.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="7.4.2" data-path="simulation-1.html"><a href="simulation-1.html#limitations-of-bootstrapping-1"><i class="fa fa-check"></i><b>7.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="simulation-1.html"><a href="simulation-1.html#fake-data-simulation-as-a-way-of-life-1"><i class="fa fa-check"></i><b>7.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="simulation-2.html"><a href="simulation-2.html"><i class="fa fa-check"></i><b>8</b> Simulation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="simulation-2.html"><a href="simulation-2.html#simulation-of-discrete-probability-models-2"><i class="fa fa-check"></i><b>8.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="simulation-2.html"><a href="simulation-2.html#how-many-girls-in-400-births-2"><i class="fa fa-check"></i><b>8.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="8.1.2" data-path="simulation-2.html"><a href="simulation-2.html#accounting-for-twins-2"><i class="fa fa-check"></i><b>8.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="simulation-2.html"><a href="simulation-2.html#simulation-of-continuous-and-mixed-discretecontinuous-models-2"><i class="fa fa-check"></i><b>8.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="simulation-2.html"><a href="simulation-2.html#simulation-in-r-using-custom-made-functions-2"><i class="fa fa-check"></i><b>8.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="simulation-2.html"><a href="simulation-2.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-2"><i class="fa fa-check"></i><b>8.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="8.4" data-path="simulation-2.html"><a href="simulation-2.html#bootstrapping-to-simulate-a-sampling-distribution-2"><i class="fa fa-check"></i><b>8.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="simulation-2.html"><a href="simulation-2.html#choices-in-defining-the-bootstrap-distribution-2"><i class="fa fa-check"></i><b>8.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="8.4.2" data-path="simulation-2.html"><a href="simulation-2.html#limitations-of-bootstrapping-2"><i class="fa fa-check"></i><b>8.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="simulation-2.html"><a href="simulation-2.html#fake-data-simulation-as-a-way-of-life-2"><i class="fa fa-check"></i><b>8.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="simulation-3.html"><a href="simulation-3.html"><i class="fa fa-check"></i><b>9</b> Simulation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="simulation-3.html"><a href="simulation-3.html#simulation-of-discrete-probability-models-3"><i class="fa fa-check"></i><b>9.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="simulation-3.html"><a href="simulation-3.html#how-many-girls-in-400-births-3"><i class="fa fa-check"></i><b>9.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="9.1.2" data-path="simulation-3.html"><a href="simulation-3.html#accounting-for-twins-3"><i class="fa fa-check"></i><b>9.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="simulation-3.html"><a href="simulation-3.html#simulation-of-continuous-and-mixed-discretecontinuous-models-3"><i class="fa fa-check"></i><b>9.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="simulation-3.html"><a href="simulation-3.html#simulation-in-r-using-custom-made-functions-3"><i class="fa fa-check"></i><b>9.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="simulation-3.html"><a href="simulation-3.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-3"><i class="fa fa-check"></i><b>9.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="9.4" data-path="simulation-3.html"><a href="simulation-3.html#bootstrapping-to-simulate-a-sampling-distribution-3"><i class="fa fa-check"></i><b>9.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="simulation-3.html"><a href="simulation-3.html#choices-in-defining-the-bootstrap-distribution-3"><i class="fa fa-check"></i><b>9.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="9.4.2" data-path="simulation-3.html"><a href="simulation-3.html#limitations-of-bootstrapping-3"><i class="fa fa-check"></i><b>9.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="simulation-3.html"><a href="simulation-3.html#fake-data-simulation-as-a-way-of-life-3"><i class="fa fa-check"></i><b>9.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="simulation-4.html"><a href="simulation-4.html"><i class="fa fa-check"></i><b>10</b> Simulation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="simulation-4.html"><a href="simulation-4.html#simulation-of-discrete-probability-models-4"><i class="fa fa-check"></i><b>10.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="simulation-4.html"><a href="simulation-4.html#how-many-girls-in-400-births-4"><i class="fa fa-check"></i><b>10.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="10.1.2" data-path="simulation-4.html"><a href="simulation-4.html#accounting-for-twins-4"><i class="fa fa-check"></i><b>10.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="simulation-4.html"><a href="simulation-4.html#simulation-of-continuous-and-mixed-discretecontinuous-models-4"><i class="fa fa-check"></i><b>10.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="simulation-4.html"><a href="simulation-4.html#simulation-in-r-using-custom-made-functions-4"><i class="fa fa-check"></i><b>10.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="simulation-4.html"><a href="simulation-4.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-4"><i class="fa fa-check"></i><b>10.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="10.4" data-path="simulation-4.html"><a href="simulation-4.html#bootstrapping-to-simulate-a-sampling-distribution-4"><i class="fa fa-check"></i><b>10.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="simulation-4.html"><a href="simulation-4.html#choices-in-defining-the-bootstrap-distribution-4"><i class="fa fa-check"></i><b>10.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="10.4.2" data-path="simulation-4.html"><a href="simulation-4.html#limitations-of-bootstrapping-4"><i class="fa fa-check"></i><b>10.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="simulation-4.html"><a href="simulation-4.html#fake-data-simulation-as-a-way-of-life-4"><i class="fa fa-check"></i><b>10.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="simulation-5.html"><a href="simulation-5.html"><i class="fa fa-check"></i><b>11</b> Simulation</a>
<ul>
<li class="chapter" data-level="11.1" data-path="simulation-5.html"><a href="simulation-5.html#simulation-of-discrete-probability-models-5"><i class="fa fa-check"></i><b>11.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="simulation-5.html"><a href="simulation-5.html#how-many-girls-in-400-births-5"><i class="fa fa-check"></i><b>11.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="11.1.2" data-path="simulation-5.html"><a href="simulation-5.html#accounting-for-twins-5"><i class="fa fa-check"></i><b>11.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="simulation-5.html"><a href="simulation-5.html#simulation-of-continuous-and-mixed-discretecontinuous-models-5"><i class="fa fa-check"></i><b>11.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="simulation-5.html"><a href="simulation-5.html#simulation-in-r-using-custom-made-functions-5"><i class="fa fa-check"></i><b>11.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="simulation-5.html"><a href="simulation-5.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-5"><i class="fa fa-check"></i><b>11.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="11.4" data-path="simulation-5.html"><a href="simulation-5.html#bootstrapping-to-simulate-a-sampling-distribution-5"><i class="fa fa-check"></i><b>11.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="simulation-5.html"><a href="simulation-5.html#choices-in-defining-the-bootstrap-distribution-5"><i class="fa fa-check"></i><b>11.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="11.4.2" data-path="simulation-5.html"><a href="simulation-5.html#limitations-of-bootstrapping-5"><i class="fa fa-check"></i><b>11.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="simulation-5.html"><a href="simulation-5.html#fake-data-simulation-as-a-way-of-life-5"><i class="fa fa-check"></i><b>11.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="simulation-6.html"><a href="simulation-6.html"><i class="fa fa-check"></i><b>12</b> Simulation</a>
<ul>
<li class="chapter" data-level="12.1" data-path="simulation-6.html"><a href="simulation-6.html#simulation-of-discrete-probability-models-6"><i class="fa fa-check"></i><b>12.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="simulation-6.html"><a href="simulation-6.html#how-many-girls-in-400-births-6"><i class="fa fa-check"></i><b>12.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="12.1.2" data-path="simulation-6.html"><a href="simulation-6.html#accounting-for-twins-6"><i class="fa fa-check"></i><b>12.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="simulation-6.html"><a href="simulation-6.html#simulation-of-continuous-and-mixed-discretecontinuous-models-6"><i class="fa fa-check"></i><b>12.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="simulation-6.html"><a href="simulation-6.html#simulation-in-r-using-custom-made-functions-6"><i class="fa fa-check"></i><b>12.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="simulation-6.html"><a href="simulation-6.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-6"><i class="fa fa-check"></i><b>12.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="12.4" data-path="simulation-6.html"><a href="simulation-6.html#bootstrapping-to-simulate-a-sampling-distribution-6"><i class="fa fa-check"></i><b>12.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="simulation-6.html"><a href="simulation-6.html#choices-in-defining-the-bootstrap-distribution-6"><i class="fa fa-check"></i><b>12.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="12.4.2" data-path="simulation-6.html"><a href="simulation-6.html#limitations-of-bootstrapping-6"><i class="fa fa-check"></i><b>12.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="simulation-6.html"><a href="simulation-6.html#fake-data-simulation-as-a-way-of-life-6"><i class="fa fa-check"></i><b>12.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="simulation-7.html"><a href="simulation-7.html"><i class="fa fa-check"></i><b>13</b> Simulation</a>
<ul>
<li class="chapter" data-level="13.1" data-path="simulation-7.html"><a href="simulation-7.html#simulation-of-discrete-probability-models-7"><i class="fa fa-check"></i><b>13.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="simulation-7.html"><a href="simulation-7.html#how-many-girls-in-400-births-7"><i class="fa fa-check"></i><b>13.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="13.1.2" data-path="simulation-7.html"><a href="simulation-7.html#accounting-for-twins-7"><i class="fa fa-check"></i><b>13.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="simulation-7.html"><a href="simulation-7.html#simulation-of-continuous-and-mixed-discretecontinuous-models-7"><i class="fa fa-check"></i><b>13.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="simulation-7.html"><a href="simulation-7.html#simulation-in-r-using-custom-made-functions-7"><i class="fa fa-check"></i><b>13.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="simulation-7.html"><a href="simulation-7.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-7"><i class="fa fa-check"></i><b>13.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="13.4" data-path="simulation-7.html"><a href="simulation-7.html#bootstrapping-to-simulate-a-sampling-distribution-7"><i class="fa fa-check"></i><b>13.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="simulation-7.html"><a href="simulation-7.html#choices-in-defining-the-bootstrap-distribution-7"><i class="fa fa-check"></i><b>13.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="13.4.2" data-path="simulation-7.html"><a href="simulation-7.html#limitations-of-bootstrapping-7"><i class="fa fa-check"></i><b>13.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="simulation-7.html"><a href="simulation-7.html#fake-data-simulation-as-a-way-of-life-7"><i class="fa fa-check"></i><b>13.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="simulation-8.html"><a href="simulation-8.html"><i class="fa fa-check"></i><b>14</b> Simulation</a>
<ul>
<li class="chapter" data-level="14.1" data-path="simulation-8.html"><a href="simulation-8.html#simulation-of-discrete-probability-models-8"><i class="fa fa-check"></i><b>14.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="simulation-8.html"><a href="simulation-8.html#how-many-girls-in-400-births-8"><i class="fa fa-check"></i><b>14.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="14.1.2" data-path="simulation-8.html"><a href="simulation-8.html#accounting-for-twins-8"><i class="fa fa-check"></i><b>14.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="simulation-8.html"><a href="simulation-8.html#simulation-of-continuous-and-mixed-discretecontinuous-models-8"><i class="fa fa-check"></i><b>14.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="simulation-8.html"><a href="simulation-8.html#simulation-in-r-using-custom-made-functions-8"><i class="fa fa-check"></i><b>14.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="simulation-8.html"><a href="simulation-8.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-8"><i class="fa fa-check"></i><b>14.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="14.4" data-path="simulation-8.html"><a href="simulation-8.html#bootstrapping-to-simulate-a-sampling-distribution-8"><i class="fa fa-check"></i><b>14.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="simulation-8.html"><a href="simulation-8.html#choices-in-defining-the-bootstrap-distribution-8"><i class="fa fa-check"></i><b>14.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="14.4.2" data-path="simulation-8.html"><a href="simulation-8.html#limitations-of-bootstrapping-8"><i class="fa fa-check"></i><b>14.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="simulation-8.html"><a href="simulation-8.html#fake-data-simulation-as-a-way-of-life-8"><i class="fa fa-check"></i><b>14.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="simulation-9.html"><a href="simulation-9.html"><i class="fa fa-check"></i><b>15</b> Simulation</a>
<ul>
<li class="chapter" data-level="15.1" data-path="simulation-9.html"><a href="simulation-9.html#simulation-of-discrete-probability-models-9"><i class="fa fa-check"></i><b>15.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="simulation-9.html"><a href="simulation-9.html#how-many-girls-in-400-births-9"><i class="fa fa-check"></i><b>15.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="15.1.2" data-path="simulation-9.html"><a href="simulation-9.html#accounting-for-twins-9"><i class="fa fa-check"></i><b>15.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="simulation-9.html"><a href="simulation-9.html#simulation-of-continuous-and-mixed-discretecontinuous-models-9"><i class="fa fa-check"></i><b>15.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="simulation-9.html"><a href="simulation-9.html#simulation-in-r-using-custom-made-functions-9"><i class="fa fa-check"></i><b>15.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="simulation-9.html"><a href="simulation-9.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-9"><i class="fa fa-check"></i><b>15.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="15.4" data-path="simulation-9.html"><a href="simulation-9.html#bootstrapping-to-simulate-a-sampling-distribution-9"><i class="fa fa-check"></i><b>15.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="simulation-9.html"><a href="simulation-9.html#choices-in-defining-the-bootstrap-distribution-9"><i class="fa fa-check"></i><b>15.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="15.4.2" data-path="simulation-9.html"><a href="simulation-9.html#limitations-of-bootstrapping-9"><i class="fa fa-check"></i><b>15.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="simulation-9.html"><a href="simulation-9.html#fake-data-simulation-as-a-way-of-life-9"><i class="fa fa-check"></i><b>15.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="simulation-10.html"><a href="simulation-10.html"><i class="fa fa-check"></i><b>16</b> Simulation</a>
<ul>
<li class="chapter" data-level="16.1" data-path="simulation-10.html"><a href="simulation-10.html#simulation-of-discrete-probability-models-10"><i class="fa fa-check"></i><b>16.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="simulation-10.html"><a href="simulation-10.html#how-many-girls-in-400-births-10"><i class="fa fa-check"></i><b>16.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="16.1.2" data-path="simulation-10.html"><a href="simulation-10.html#accounting-for-twins-10"><i class="fa fa-check"></i><b>16.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="simulation-10.html"><a href="simulation-10.html#simulation-of-continuous-and-mixed-discretecontinuous-models-10"><i class="fa fa-check"></i><b>16.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="simulation-10.html"><a href="simulation-10.html#simulation-in-r-using-custom-made-functions-10"><i class="fa fa-check"></i><b>16.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="simulation-10.html"><a href="simulation-10.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-10"><i class="fa fa-check"></i><b>16.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="16.4" data-path="simulation-10.html"><a href="simulation-10.html#bootstrapping-to-simulate-a-sampling-distribution-10"><i class="fa fa-check"></i><b>16.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="simulation-10.html"><a href="simulation-10.html#choices-in-defining-the-bootstrap-distribution-10"><i class="fa fa-check"></i><b>16.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="16.4.2" data-path="simulation-10.html"><a href="simulation-10.html#limitations-of-bootstrapping-10"><i class="fa fa-check"></i><b>16.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="simulation-10.html"><a href="simulation-10.html#fake-data-simulation-as-a-way-of-life-10"><i class="fa fa-check"></i><b>16.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="simulation-11.html"><a href="simulation-11.html"><i class="fa fa-check"></i><b>17</b> Simulation</a>
<ul>
<li class="chapter" data-level="17.1" data-path="simulation-11.html"><a href="simulation-11.html#simulation-of-discrete-probability-models-11"><i class="fa fa-check"></i><b>17.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="simulation-11.html"><a href="simulation-11.html#how-many-girls-in-400-births-11"><i class="fa fa-check"></i><b>17.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="17.1.2" data-path="simulation-11.html"><a href="simulation-11.html#accounting-for-twins-11"><i class="fa fa-check"></i><b>17.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="simulation-11.html"><a href="simulation-11.html#simulation-of-continuous-and-mixed-discretecontinuous-models-11"><i class="fa fa-check"></i><b>17.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="simulation-11.html"><a href="simulation-11.html#simulation-in-r-using-custom-made-functions-11"><i class="fa fa-check"></i><b>17.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="simulation-11.html"><a href="simulation-11.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-11"><i class="fa fa-check"></i><b>17.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="17.4" data-path="simulation-11.html"><a href="simulation-11.html#bootstrapping-to-simulate-a-sampling-distribution-11"><i class="fa fa-check"></i><b>17.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="simulation-11.html"><a href="simulation-11.html#choices-in-defining-the-bootstrap-distribution-11"><i class="fa fa-check"></i><b>17.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="17.4.2" data-path="simulation-11.html"><a href="simulation-11.html#limitations-of-bootstrapping-11"><i class="fa fa-check"></i><b>17.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="simulation-11.html"><a href="simulation-11.html#fake-data-simulation-as-a-way-of-life-11"><i class="fa fa-check"></i><b>17.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="simulation-12.html"><a href="simulation-12.html"><i class="fa fa-check"></i><b>18</b> Simulation</a>
<ul>
<li class="chapter" data-level="18.1" data-path="simulation-12.html"><a href="simulation-12.html#simulation-of-discrete-probability-models-12"><i class="fa fa-check"></i><b>18.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="simulation-12.html"><a href="simulation-12.html#how-many-girls-in-400-births-12"><i class="fa fa-check"></i><b>18.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="18.1.2" data-path="simulation-12.html"><a href="simulation-12.html#accounting-for-twins-12"><i class="fa fa-check"></i><b>18.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="simulation-12.html"><a href="simulation-12.html#simulation-of-continuous-and-mixed-discretecontinuous-models-12"><i class="fa fa-check"></i><b>18.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="simulation-12.html"><a href="simulation-12.html#simulation-in-r-using-custom-made-functions-12"><i class="fa fa-check"></i><b>18.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="simulation-12.html"><a href="simulation-12.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-12"><i class="fa fa-check"></i><b>18.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="18.4" data-path="simulation-12.html"><a href="simulation-12.html#bootstrapping-to-simulate-a-sampling-distribution-12"><i class="fa fa-check"></i><b>18.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="simulation-12.html"><a href="simulation-12.html#choices-in-defining-the-bootstrap-distribution-12"><i class="fa fa-check"></i><b>18.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="18.4.2" data-path="simulation-12.html"><a href="simulation-12.html#limitations-of-bootstrapping-12"><i class="fa fa-check"></i><b>18.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="simulation-12.html"><a href="simulation-12.html#fake-data-simulation-as-a-way-of-life-12"><i class="fa fa-check"></i><b>18.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="simulation-13.html"><a href="simulation-13.html"><i class="fa fa-check"></i><b>19</b> Simulation</a>
<ul>
<li class="chapter" data-level="19.1" data-path="simulation-13.html"><a href="simulation-13.html#simulation-of-discrete-probability-models-13"><i class="fa fa-check"></i><b>19.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="simulation-13.html"><a href="simulation-13.html#how-many-girls-in-400-births-13"><i class="fa fa-check"></i><b>19.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="19.1.2" data-path="simulation-13.html"><a href="simulation-13.html#accounting-for-twins-13"><i class="fa fa-check"></i><b>19.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="simulation-13.html"><a href="simulation-13.html#simulation-of-continuous-and-mixed-discretecontinuous-models-13"><i class="fa fa-check"></i><b>19.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="simulation-13.html"><a href="simulation-13.html#simulation-in-r-using-custom-made-functions-13"><i class="fa fa-check"></i><b>19.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="simulation-13.html"><a href="simulation-13.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-13"><i class="fa fa-check"></i><b>19.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="19.4" data-path="simulation-13.html"><a href="simulation-13.html#bootstrapping-to-simulate-a-sampling-distribution-13"><i class="fa fa-check"></i><b>19.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="19.4.1" data-path="simulation-13.html"><a href="simulation-13.html#choices-in-defining-the-bootstrap-distribution-13"><i class="fa fa-check"></i><b>19.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="19.4.2" data-path="simulation-13.html"><a href="simulation-13.html#limitations-of-bootstrapping-13"><i class="fa fa-check"></i><b>19.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="simulation-13.html"><a href="simulation-13.html#fake-data-simulation-as-a-way-of-life-13"><i class="fa fa-check"></i><b>19.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="simulation-14.html"><a href="simulation-14.html"><i class="fa fa-check"></i><b>20</b> Simulation</a>
<ul>
<li class="chapter" data-level="20.1" data-path="simulation-14.html"><a href="simulation-14.html#simulation-of-discrete-probability-models-14"><i class="fa fa-check"></i><b>20.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="simulation-14.html"><a href="simulation-14.html#how-many-girls-in-400-births-14"><i class="fa fa-check"></i><b>20.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="20.1.2" data-path="simulation-14.html"><a href="simulation-14.html#accounting-for-twins-14"><i class="fa fa-check"></i><b>20.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="simulation-14.html"><a href="simulation-14.html#simulation-of-continuous-and-mixed-discretecontinuous-models-14"><i class="fa fa-check"></i><b>20.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="simulation-14.html"><a href="simulation-14.html#simulation-in-r-using-custom-made-functions-14"><i class="fa fa-check"></i><b>20.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="simulation-14.html"><a href="simulation-14.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-14"><i class="fa fa-check"></i><b>20.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="20.4" data-path="simulation-14.html"><a href="simulation-14.html#bootstrapping-to-simulate-a-sampling-distribution-14"><i class="fa fa-check"></i><b>20.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="simulation-14.html"><a href="simulation-14.html#choices-in-defining-the-bootstrap-distribution-14"><i class="fa fa-check"></i><b>20.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="20.4.2" data-path="simulation-14.html"><a href="simulation-14.html#limitations-of-bootstrapping-14"><i class="fa fa-check"></i><b>20.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="simulation-14.html"><a href="simulation-14.html#fake-data-simulation-as-a-way-of-life-14"><i class="fa fa-check"></i><b>20.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="simulation-15.html"><a href="simulation-15.html"><i class="fa fa-check"></i><b>21</b> Simulation</a>
<ul>
<li class="chapter" data-level="21.1" data-path="simulation-15.html"><a href="simulation-15.html#simulation-of-discrete-probability-models-15"><i class="fa fa-check"></i><b>21.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="21.1.1" data-path="simulation-15.html"><a href="simulation-15.html#how-many-girls-in-400-births-15"><i class="fa fa-check"></i><b>21.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="21.1.2" data-path="simulation-15.html"><a href="simulation-15.html#accounting-for-twins-15"><i class="fa fa-check"></i><b>21.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="simulation-15.html"><a href="simulation-15.html#simulation-of-continuous-and-mixed-discretecontinuous-models-15"><i class="fa fa-check"></i><b>21.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="simulation-15.html"><a href="simulation-15.html#simulation-in-r-using-custom-made-functions-15"><i class="fa fa-check"></i><b>21.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="simulation-15.html"><a href="simulation-15.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-15"><i class="fa fa-check"></i><b>21.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="21.4" data-path="simulation-15.html"><a href="simulation-15.html#bootstrapping-to-simulate-a-sampling-distribution-15"><i class="fa fa-check"></i><b>21.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="21.4.1" data-path="simulation-15.html"><a href="simulation-15.html#choices-in-defining-the-bootstrap-distribution-15"><i class="fa fa-check"></i><b>21.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="21.4.2" data-path="simulation-15.html"><a href="simulation-15.html#limitations-of-bootstrapping-15"><i class="fa fa-check"></i><b>21.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="21.5" data-path="simulation-15.html"><a href="simulation-15.html#fake-data-simulation-as-a-way-of-life-15"><i class="fa fa-check"></i><b>21.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="simulation-16.html"><a href="simulation-16.html"><i class="fa fa-check"></i><b>22</b> Simulation</a>
<ul>
<li class="chapter" data-level="22.1" data-path="simulation-16.html"><a href="simulation-16.html#simulation-of-discrete-probability-models-16"><i class="fa fa-check"></i><b>22.1</b> Simulation of discrete probability models</a>
<ul>
<li class="chapter" data-level="22.1.1" data-path="simulation-16.html"><a href="simulation-16.html#how-many-girls-in-400-births-16"><i class="fa fa-check"></i><b>22.1.1</b> How many girls in 400 births?</a></li>
<li class="chapter" data-level="22.1.2" data-path="simulation-16.html"><a href="simulation-16.html#accounting-for-twins-16"><i class="fa fa-check"></i><b>22.1.2</b> Accounting for twins</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="simulation-16.html"><a href="simulation-16.html#simulation-of-continuous-and-mixed-discretecontinuous-models-16"><i class="fa fa-check"></i><b>22.2</b> Simulation of continuous and mixed discrete/continuous models</a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="simulation-16.html"><a href="simulation-16.html#simulation-in-r-using-custom-made-functions-16"><i class="fa fa-check"></i><b>22.2.1</b> Simulation in R using custom-made functions</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="simulation-16.html"><a href="simulation-16.html#summarizing-a-set-of-simulations-using-median-and-median-absolute-deviation-16"><i class="fa fa-check"></i><b>22.3</b> Summarizing a set of simulations using median and median absolute deviation</a></li>
<li class="chapter" data-level="22.4" data-path="simulation-16.html"><a href="simulation-16.html#bootstrapping-to-simulate-a-sampling-distribution-16"><i class="fa fa-check"></i><b>22.4</b> Bootstrapping to simulate a sampling distribution</a>
<ul>
<li class="chapter" data-level="22.4.1" data-path="simulation-16.html"><a href="simulation-16.html#choices-in-defining-the-bootstrap-distribution-16"><i class="fa fa-check"></i><b>22.4.1</b> Choices in defining the bootstrap distribution</a></li>
<li class="chapter" data-level="22.4.2" data-path="simulation-16.html"><a href="simulation-16.html#limitations-of-bootstrapping-16"><i class="fa fa-check"></i><b>22.4.2</b> Limitations of bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="22.5" data-path="simulation-16.html"><a href="simulation-16.html#fake-data-simulation-as-a-way-of-life-16"><i class="fa fa-check"></i><b>22.5</b> Fake-data simulation as a way of life</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html"><i class="fa fa-check"></i><b>23</b> Exercises of Regression and Other Stories</a>
<ul>
<li class="chapter" data-level="23.1" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#overview-1"><i class="fa fa-check"></i><b>23.1</b> Overview</a>
<ul>
<li class="chapter" data-level="23.1.1" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#from-design-to-decision"><i class="fa fa-check"></i><b>23.1.1</b> From design to decision</a></li>
<li class="chapter" data-level="23.1.2" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#sketching-a-regression-model-and-data"><i class="fa fa-check"></i><b>23.1.2</b> Sketching a regression model and data</a></li>
<li class="chapter" data-level="23.1.3" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#goals-of-regression"><i class="fa fa-check"></i><b>23.1.3</b> Goals of regression</a></li>
<li class="chapter" data-level="23.1.4" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#problems-of-statistics"><i class="fa fa-check"></i><b>23.1.4</b> Problems of statistics</a></li>
<li class="chapter" data-level="23.1.5" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#goals-of-regression-1"><i class="fa fa-check"></i><b>23.1.5</b> Goals of regression</a></li>
</ul></li>
<li class="chapter" data-level="23.2" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#causal-inference"><i class="fa fa-check"></i><b>23.2</b> Causal inference</a></li>
<li class="chapter" data-level="23.3" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#statistics-as-generalization"><i class="fa fa-check"></i><b>23.3</b> Statistics as generalization</a></li>
<li class="chapter" data-level="23.4" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#statistics-as-generalization-1"><i class="fa fa-check"></i><b>23.4</b> Statistics as generalization</a></li>
<li class="chapter" data-level="23.5" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#a-problem-with-linear-models"><i class="fa fa-check"></i><b>23.5</b> A problem with linear models</a>
<ul>
<li class="chapter" data-level="23.5.1" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#working-through-your-own-example"><i class="fa fa-check"></i><b>23.5.1</b> Working through your own example</a></li>
</ul></li>
<li class="chapter" data-level="23.6" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#some-basic-methods-in-mathematics-and-probability-1"><i class="fa fa-check"></i><b>23.6</b> Some basic methods in mathematics and probability</a>
<ul>
<li class="chapter" data-level="23.6.1" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#weighted-averages-2"><i class="fa fa-check"></i><b>23.6.1</b> Weighted averages</a></li>
<li class="chapter" data-level="23.6.2" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#weighted-averages-3"><i class="fa fa-check"></i><b>23.6.2</b> Weighted averages</a></li>
<li class="chapter" data-level="23.6.3" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#probability-distributions-1"><i class="fa fa-check"></i><b>23.6.3</b> Probability distributions</a></li>
<li class="chapter" data-level="23.6.4" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#probability-distributions-2"><i class="fa fa-check"></i><b>23.6.4</b> Probability distributions</a></li>
<li class="chapter" data-level="23.6.5" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#probability-distributions-3"><i class="fa fa-check"></i><b>23.6.5</b> Probability distributions</a></li>
<li class="chapter" data-level="23.6.6" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#linear-transformations-2"><i class="fa fa-check"></i><b>23.6.6</b> Linear transformations</a></li>
<li class="chapter" data-level="23.6.7" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#linear-transformations-3"><i class="fa fa-check"></i><b>23.6.7</b> Linear transformations</a></li>
<li class="chapter" data-level="23.6.8" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#correlated-random-variables"><i class="fa fa-check"></i><b>23.6.8</b> Correlated random variables</a></li>
<li class="chapter" data-level="23.6.9" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#comparison-of-distributions"><i class="fa fa-check"></i><b>23.6.9</b> Comparison of distributions</a></li>
<li class="chapter" data-level="23.6.10" data-path="exercises-of-regression-and-other-stories.html"><a href="exercises-of-regression-and-other-stories.html#working-through-your-own-example-1"><i class="fa fa-check"></i><b>23.6.10</b> Working through your own example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Reading Notes for Regression and Other Stories</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="background-on-regression-modeling" class="section level1" number="6">
<h1><span class="header-section-number">Chapter 6</span> Background on regression modeling</h1>
<p>순수하게 수학적인 측면에서 회귀모델은 두 가지 목적을 갖는다: 예측(prediction)과 비교(comparison)이다.</p>
<ol style="list-style-type: decimal">
<li><p>주어진 일련의 투입(설명변수/예측변수)을 가지고 결과(종속변수/결과변수)의 분포를 예측하는 것.</p></li>
<li><p>투입(설명변수/예측변수)의 서로 다른 값들에 대해 이 예측들이 어떻게 달라지는지를 집단 간 단순비교 혹은 인과효과의 추정 등을 통해 비교하는 것.</p></li>
</ol>
<div id="regression-models" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Regression models</h2>
<p>가장 단순한 회귀모델은 하나의 예측변수를 가진 선형모델이다.</p>
<p><span class="math display">\[
\text{Basic regression model}: y = a + bx + \mathrm{error}.
\]</span></p>
<p><span class="math inline">\(a\)</span>와 <span class="math inline">\(b\)</span>는 <em>계수(coefficients)</em>, 혹은 보다 일반적으로 모델의 <em>모수(parameters</em>라고 한다. 단순선형모델은 여러 가지 방식으로 정교해질(복잡해질) 수 있으며, 다음과 같은 내용들을 포함할 수 있다.</p>
<ul>
<li><p>추가적인 예측변수들(Additional predictors)</p>
<ul>
<li><p><span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k + \mathrm{error}\)</span></p></li>
<li><p>벡터-매트릭스 식으로는 <span class="math inline">\(y = X\beta + \mathrm{error}\)</span>라고 쓸 수 있다.</p></li>
</ul></li>
<li><p>비선형모델(Nonlinear models): <span class="math inline">\(\log y = a + b \log x + \mathrm{error}\)</span>.</p></li>
<li><p>비가산모델(Nonadditive models)</p>
<ul>
<li><p>예측변수 <span class="math inline">\(x_1\)</span>과 <span class="math inline">\(x_2\)</span> 간의 상호작용을 포함</p></li>
<li><p><span class="math inline">\(\log y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_1 x_2 + \mathrm{error}\)</span>.</p></li>
</ul></li>
<li><p>일반화선형모델(<em>Generalized linear models</em>)</p>
<ul>
<li>정규분포인데다 다른 예측변수들에 독립적인 오차들을 가지고 있어 적합이 되지 않는 이산형 종속변수나 다른 데이터에 사용하는 선형회귀모델.</li>
</ul></li>
<li><p>비모수모델(<em>Nonparametric models</em>)</p>
<ul>
<li>주어진 <span class="math inline">\(x\)</span>에 따라 <span class="math inline">\(y\)</span>의 예측값에 대해 자의적인 곡선을 그릴 수 잇게 하는 수많은 모수들을 포함하는 모델.</li>
</ul></li>
<li><p>멀티레벨모델(<em>Multilevel models</em>)</p>
<ul>
<li>회귀모델의 계수는 집단 또는 시뮬레이션에 따라서 변할 수 있다. 멀티레벨 모델은 하나 이상의 분석수준을 가진 모델을 의미한다.</li>
</ul></li>
<li><p>측정-오차 모델(<em>Measurement-error models</em>)</p>
<ul>
<li>예측변수 <span class="math inline">\(x\)</span>와 결과변수 <span class="math inline">\(y\)</span>가 오차와 함께 측정되고, 핵심 통계치 간의 관계를 추정하고자 할 때 사용하는 모델.</li>
</ul></li>
</ul>
<p><span class="citation"><a href="#ref-ghv2020" role="doc-biblioref">Gelman, Hill, and Vehtari</a> (<a href="#ref-ghv2020" role="doc-biblioref">2020</a>)</span> 에서는 선형회귀모델 중 가산형(additive), 비선형(nonlinear), 비가산형(nonadditive, 곱산형; multiplicative), 그리고 일반화 선형 모델에 대해 다룬다.</p>
</div>
<div id="fitting-a-simple-regression-to-fake-data" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Fitting a simple regression to fake data</h2>
<p>20개의 관측치를 가지는 페이크데이터 <span class="math inline">\(y_i\)</span>가 예측변수 <span class="math inline">\(x_i\)</span>는 1부터 20까지의 값을 가지고, 절편은 <span class="math inline">\(a = 0.2\)</span>, 기울기는 <span class="math inline">\(b=0.3\)</span>, 오차는 평균 0, 표준편차(<span class="math inline">\(\sigma\)</span>)가 0.5인 정규분포를 따르는 모델 <span class="math inline">\(y_i = a + b x_i + \epsilon_i\)</span>로부터 시뮬레이션된다고 하자. 우리는 이 모델로부터 약 2/3에 해당하는 관측치들이 <span class="math inline">\(\pm \text{표준오차}\)</span> 범주에 위치한다고 할 때, 이같은 페이크데이터는 다음과 같이 만들 수 있다.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="background-on-regression-modeling.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb39-2"><a href="background-on-regression-modeling.html#cb39-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span></span>
<span id="cb39-3"><a href="background-on-regression-modeling.html#cb39-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb39-4"><a href="background-on-regression-modeling.html#cb39-4" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fl">0.2</span></span>
<span id="cb39-5"><a href="background-on-regression-modeling.html#cb39-5" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fl">0.3</span></span>
<span id="cb39-6"><a href="background-on-regression-modeling.html#cb39-6" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb39-7"><a href="background-on-regression-modeling.html#cb39-7" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> a <span class="sc">+</span> b <span class="sc">*</span> x <span class="sc">+</span> sigma <span class="sc">*</span> <span class="fu">rnorm</span>(n)</span></code></pre></div>
<div id="fitting-a-regression-and-displaying-the-results" class="section level3" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Fitting a regression and displaying the results</h3>
<p>모델을 적합하기 위해서 예측변수와 종속변수를 포함하는 데이터프레임, <code>fake</code>를 만들어보자.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="background-on-regression-modeling.html#cb40-1" aria-hidden="true" tabindex="-1"></a>fake <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, y)</span></code></pre></div>
<p><span class="citation"><a href="#ref-ghv2020" role="doc-biblioref">Gelman, Hill, and Vehtari</a> (<a href="#ref-ghv2020" role="doc-biblioref">2020</a>)</span> 은 <code>stan_glm()</code>을 이용해서 일반화선형모델을 추정, 시뮬레이션된 계수의 중앙값과 <code>mad sd</code>를 계산해서 제시한다. 하지만 여기서는 일반적으로 사용하는 <code>lm()</code>을 사용하여 회귀모델을 추정한다.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="background-on-regression-modeling.html#cb41-1" aria-hidden="true" tabindex="-1"></a>fit_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> fake)</span>
<span id="cb41-2"><a href="background-on-regression-modeling.html#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x, data = fake)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.13428 -0.38216 -0.05455  0.43228  1.05894 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.21588    0.29055   0.743    0.467    
## x            0.30394    0.02425  12.531 2.51e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6255 on 18 degrees of freedom
## Multiple R-squared:  0.8972, Adjusted R-squared:  0.8914 
## F-statistic:   157 on 1 and 18 DF,  p-value: 2.506e-10</code></pre>
<p>분석 결과, 추정된 절편은 약 0.16의 불확성을 가지고 평균적으로 0.29의 값을 가진다. 추정된 기울기는 0.01의 불확실성을 가지고 0.3의 평균값을 가진다. 잔차의 표준오차는 0.34이다.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="background-on-regression-modeling.html#cb43-1" aria-hidden="true" tabindex="-1"></a>fitted_1 <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">augment</span>(fit_1)</span>
<span id="cb43-2"><a href="background-on-regression-modeling.html#cb43-2" aria-hidden="true" tabindex="-1"></a>a_hat <span class="ot">&lt;-</span> <span class="fu">coef</span>(fit_1)[<span class="dv">1</span>]</span>
<span id="cb43-3"><a href="background-on-regression-modeling.html#cb43-3" aria-hidden="true" tabindex="-1"></a>b_hat <span class="ot">&lt;-</span> <span class="fu">coef</span>(fit_1)[<span class="dv">2</span>]</span>
<span id="cb43-4"><a href="background-on-regression-modeling.html#cb43-4" aria-hidden="true" tabindex="-1"></a>fitted_1 <span class="sc">%&gt;%</span> </span>
<span id="cb43-5"><a href="background-on-regression-modeling.html#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(x, y)) <span class="sc">+</span> </span>
<span id="cb43-6"><a href="background-on-regression-modeling.html#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">shape =</span> <span class="dv">21</span>) <span class="sc">+</span> </span>
<span id="cb43-7"><a href="background-on-regression-modeling.html#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> a_hat, <span class="at">slope =</span> b_hat) <span class="sc">+</span> </span>
<span id="cb43-8"><a href="background-on-regression-modeling.html#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">&quot;Data and fitted regression line&quot;</span>) <span class="sc">+</span> </span>
<span id="cb43-9"><a href="background-on-regression-modeling.html#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">mean</span>(x) <span class="sc">+</span> <span class="dv">3</span>, <span class="at">y =</span> a_hat <span class="sc">+</span> b_hat<span class="sc">*</span><span class="fu">mean</span>(x)), </span>
<span id="cb43-10"><a href="background-on-regression-modeling.html#cb43-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">&quot;y =&quot;</span>, <span class="fu">round</span>(a_hat, <span class="dv">2</span>), <span class="st">&quot;+&quot;</span>, </span>
<span id="cb43-11"><a href="background-on-regression-modeling.html#cb43-11" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">round</span>(b_hat, <span class="dv">2</span>), <span class="st">&quot;* x&quot;</span>)) <span class="sc">+</span> </span>
<span id="cb43-12"><a href="background-on-regression-modeling.html#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">7</span>, <span class="dv">1</span>))) <span class="sc">+</span> </span>
<span id="cb43-13"><a href="background-on-regression-modeling.html#cb43-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-57"></span>
<img src="regression-ghv_files/figure-html/unnamed-chunk-57-1.png" alt="Simple example of a regression line fit to fake data. The 20 data points were simulated from the model, $y = 0.2 + 0.3x + \text{error}$, with errors that were independent and normally distributed with mean 0 and standard deviation 0.5." width="672" />
<p class="caption">
Figure 6.1: Simple example of a regression line fit to fake data. The 20 data points were simulated from the model, <span class="math inline">\(y = 0.2 + 0.3x + \text{error}\)</span>, with errors that were independent and normally distributed with mean 0 and standard deviation 0.5.
</p>
</div>
</div>
<div id="comparing-estimates-to-assumed-parameter-values" class="section level3" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> Comparing estimates to assumed parameter values</h3>
<p>페이크데이터에 모델을 적합하면, 모수에 대한 추정치와 가정된 값 간의 비교가 가능하다. 이 리딩노트에서는 <code>stan</code>을 이용한 시뮬레이션을 수행한 것이 아니기 때문에 <span class="math inline">\(\sigma\)</span>에 대한 불확실성은 추정되지 않는다.</p>
<table>
<caption>
<span id="tab:unnamed-chunk-58">Table 6.1: </span>After simulating 20 fake data points from a simple linear regression, <span class="math inline">\(y_i = a + b x_i + \epsilon_i\)</span> , with errors <span class="math inline">\(\epsilon_i\)</span> drawn from a normal distribution with mean 0 and standard deviation <span class="math inline">\(\sigma\)</span>, we then fit a linear regression to these data and obtain estimates and uncertainties for the three parameters from the model. We can then see that the estimates are roughly consistent with the specified parameter values
</caption>
<thead>
<tr>
<th style="text-align:left;">
Parameter
</th>
<th style="text-align:right;">
Assumed value
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Uncertainty
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a\)</span>
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:right;">
0.29
</td>
<td style="text-align:right;">
0.16
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(b\)</span>
</td>
<td style="text-align:right;">
0.3
</td>
<td style="text-align:right;">
0.30
</td>
<td style="text-align:right;">
0.01
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sigma\)</span>
</td>
<td style="text-align:right;">
0.5
</td>
<td style="text-align:right;">
0.34
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
<p>결과를 해석해보면 다음과 같다.</p>
<ul>
<li><p>우리는 모집단에서의 절편 <span class="math inline">\(a\)</span>가 0.2일 것으로 기대했고, 페이크데이터로 모델이 추정한 결과는 0.29, 불확실성은 0.16이다.</p></li>
<li><p>추정된 절편값과 모수로 가정한 값의 차이는 0.09이다. 하지만 절편에 대한 불확실성은 0.16이다.</p></li>
<li><p>즉, 추정치와 실제 값(모수) 간의 차이는 1 표준오차보다 작다. 두 값의 차이는 불확실성으로 인해 나타날 수 있는 차이에 비해 오히려 작은 것이다. 과연 이 경우에 우리는 추정된 결과가 불확실성으로 인한 것일지 혹은 진짜 모수와 표본으로부터 얻은 결과가 차이가 있어서 나타난 차이일지 구분할 수 있을까?</p></li>
</ul>
</div>
</div>
<div id="interpret-coefficients-as-comparisons-not-effects" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Interpret coefficients as comparisons, not effects</h2>
<p>회귀계수는 종종 “효과”라고 불리지만, 이 용어는 오해의 소지가 있다. 1816명의 응답자를 대상으로 한 설문데이터로 키(인치), 성별로 연간 소득(천 달러)을 예측하는 회귀모델을 적합하는 예제를 살펴보자.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="background-on-regression-modeling.html#cb44-1" aria-hidden="true" tabindex="-1"></a>earnings<span class="sc">$</span>earnk <span class="ot">&lt;-</span> earnings<span class="sc">$</span>earn<span class="sc">/</span><span class="dv">1000</span></span>
<span id="cb44-2"><a href="background-on-regression-modeling.html#cb44-2" aria-hidden="true" tabindex="-1"></a>fit_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(earnk <span class="sc">~</span> height <span class="sc">+</span> male, <span class="at">data=</span>earnings)</span>
<span id="cb44-3"><a href="background-on-regression-modeling.html#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = earnk ~ height + male, data = earnings)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -31.99 -12.47  -3.53   7.05 368.66 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -25.8722    11.9615  -2.163  0.03068 *  
## height        0.6470     0.1852   3.493  0.00049 ***
## male         10.6327     1.4683   7.241 6.53e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.39 on 1813 degrees of freedom
## Multiple R-squared:  0.09962,    Adjusted R-squared:  0.09862 
## F-statistic: 100.3 on 2 and 1813 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>위의 분석 결과를 바탕으로 적합된 모델을 다시 써보면 다음과 같이 나타낼 수 있다.</p>
<p><span class="math display">\[
\text{earnings} = -25.9 + 0.6 \times \text{height} + 10.6 \times \text{male} + \text{error}.
\]</span></p>
<p><span class="math inline">\(\sigma\)</span>, 잔차의 표준편차는 21.4로 나타나는데 이 결과는 연간 소득 관측치의 약 68%가 선형 예측변수의 <span class="math inline">\(\pm \$21,400\)</span> 범주 안에 위치하고, 약 95% 관측치가 <span class="math inline">\(2\pm2\times\$21,400 = \$42,800\)</span>의 범주 안에 위치할 것이라는 점을 보여준다. 이때, 이 68%, 95%는 정규분포에 대한 특징에서 유도된 것이다.</p>
<p>데이터의 표준편차와 추정된 설명변동량의 비율을 비교하면 잔차의 표준편차에 대해 감을 잡을 수 있다.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="background-on-regression-modeling.html#cb46-1" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sigma</span>(fit_2)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sd</span>(earnings<span class="sc">$</span>earnk)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<p><span class="math inline">\(R^2=0.10\)</span>은 이 데이터에서 선형모델이 연간소득 변수의 약 10%를 설명한다는 것을 의미한다. 즉, 성별과 키만 가지고는 연간소득의 약 10%만 설명할 수 있다는 것이다.</p>
<p>한편, 적합된 모델을 과대해석하지 않도록 주의를 기울여야만 한다. 많은 가정들을 제외하더라도 예측변수와 결과변수 간의 관계-회귀계수를 “효과”라고 표현하는 것은 부적절하다. 왜냐하면 “효과”란 어떠한 “처치”나 “개임”과 관련되어 나타나는 변화로 정의하기 때문이다. “키가 연간 소득에 미치는 효과”가 $600이라고 말하는 것은 누군가의 키를 1인치 늘리면 그의 연간소득이 약 $600 증가할 것이라고 기대할 수 있다는 것을 의미한다. 그러나 이는 모델에서 추정된 결과는 아니다. 오히려 모델에서 추정된 것은 관측데이터를 통해 볼 수 있는 패턴-그 표본에서는 키가 큰 사람일수록 평균적으로 더 높은 연간소득을 가질 것이라는 것에 불과하다. 왜냐하면 실험 설계와 다르게 앞선 선형회귀모델에서는 키와 연간소득의 관계에서 연간소득에 영향을 미칠 수 있는 다른 변수들의 효과가 완벽하게 통제되지 않았기 때문이다.</p>
<p>그렇다면 적합된 모델에서 키에 대한 계수를 어떻게 생각할 수 있을까? “적합된 모델에서, 연간소득의 평균차이는 동일한 성별을 가지고 있지만 1인치 차이가 나는 두 사람을 비교했을 때, $600이다.”라고 말할 수 있다. 즉, <strong>회귀모델의 가장 안전한 해석은 비교로 해석하는 것이다.</strong></p>
<p>마찬가지로 추정된 “성별의 효과”가 $10,600이라고 말하는 것은 부적절하다. “적합된 모델에 따르면, 동일한 키를 가지고 있지만 성별만 다른 두 사람을 비교했을 때, 남성의 연간소득이 평균적으로 여성의 연간소득보다 $10,600 더 높을 것이다.”라고 해석하는 것이 적절하다.</p>
<p>정리하자면, 회귀모델은 예측을 위한 수리적 도구이다. 회귀계수는 때론 효과로 해석될 수 있지만, 그보다는 평균의 비교로 해석되는 것이 더 바람직하다.</p>
</div>
<div id="historical-origins-of-regression" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Historical origins of regression</h2>
<p>회귀(regression)이라는 개념을 Francis Galton으로부터 유래되었는데, 그는 사람의 키가 유전되는 것인지를 이해하기 위해 선형 모델을 적합해본 사람이다. 아이의 키가 부모로부터 유전되는가를 예측하면서, 그는 키가 큰 부모를 둔 아이의 키가 키가 작은 부모를 둔 아이들에 비하여 평균적으로 더 키가 큰 것을 확인하였다. 그 반대의 경우도 마찬가지였다. 즉, 사람의 키는 세대가 지남에 따라서 “평균으로 회귀”한다는 것을 발견했고, 회귀가 통계적 용어로 사용되기 시작한 것이다.</p>
<div id="daughters-heights-regressing-to-the-mean" class="section level3" number="6.4.1">
<h3><span class="header-section-number">6.4.1</span> Daughters’ heights “regressing” to the mean</h3>
<p>1903년 Karl Pearson과 Alice Lee의 유전에 관한 고전적 연구를 살펴보자.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-61"></span>
<img src="regression-ghv_files/figure-html/unnamed-chunk-61-1.png" alt="(a) Scatterplot adapted from data from Pearson and Lee (1903) of the heights of mothers and their adult daughters, along with the regression line predicting daughters’ from mothers’ heights. (b) The  regression line by itself, just to make the pattern easier to see. The line automatically goes through the mean of the data, and it has a slope of 0.54, implying that, on average, the difference of a daughter’s height from the average (mean) of women’s heights is only about half the difference of her mother’s height from the average." width="672" />
<p class="caption">
Figure 6.2: (a) Scatterplot adapted from data from Pearson and Lee (1903) of the heights of mothers and their adult daughters, along with the regression line predicting daughters’ from mothers’ heights. (b) The regression line by itself, just to make the pattern easier to see. The line automatically goes through the mean of the data, and it has a slope of 0.54, implying that, on average, the difference of a daughter’s height from the average (mean) of women’s heights is only about half the difference of her mother’s height from the average.
</p>
</div>
<p>Figure 6.2a는 엄마와 딸의 키에 대한 데이터를 엄마의 키로부터 딸의 키를 예측하는 가장 잘 맞는 선-회귀선(<em>regression line</em>)에 따라서 배열한 것이다. 회귀선은 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span>의 평균을 지나간다.</p>
<p>Figure 6.2b는 회귀선, <span class="math inline">\(y = 30 + 0.54x\)</span>만을 보여준다. <span class="math inline">\(y = 30 + 0.54x + \text{error}\)</span>라고도 쓸 수 있다. 여기서 오차를 포함하는 이유는 모델이 각각의 관측치들에 완벽하게 들어맞지는 않는다는 것을 강조하기 위함이다.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-62"></span>
<img src="regression-ghv_files/figure-html/unnamed-chunk-62-1.png" alt="(a) Fitted regression line, $y = 30 + 0.54 x$, graphed using intercept and slope. (b) Difficulty of the intercept-slope formulation in the context of the data in the height example. The intercept of 30 inches corresponds to the predicted height of a daughter whose mother is a meaningless 0 inches tall." width="672" />
<p class="caption">
Figure 6.3: (a) Fitted regression line, <span class="math inline">\(y = 30 + 0.54 x\)</span>, graphed using intercept and slope. (b) Difficulty of the intercept-slope formulation in the context of the data in the height example. The intercept of 30 inches corresponds to the predicted height of a daughter whose mother is a meaningless 0 inches tall.
</p>
</div>
<p>Figure 6.3a는 회귀분석 결과를 절편-기울기의 형태로 나타내며 가장 시각화하기 쉬운 방식이다. 하지만 현실 세계를 기술하는 데 있어서 이러한 회귀선은 문제를 야기할 수 있다. Figure 6.3b를 보면 실제 데이터를 예측한 회귀선이 데이터가 존재하지 않는 지점까지 뻗어나가는 것을 확인할 수 있다. 현실 세계에서 키가 0인 사람은 존재하지 않는다. 선형모델을 통한 예측을 했을 때, 그 결과는 데이터에 미루어 합리적인 것이어야 한다. 어디까지가 우리가 실질적으로 이해할 수 있는 함의를 제공하는지를 판단하는 것은 연구자의 몫이 될 것이다.</p>
</div>
<div id="fitting-the-model-in-r" class="section level3" number="6.4.2">
<h3><span class="header-section-number">6.4.2</span> Fitting the model in R</h3>
<p>앞서 <span class="math inline">\(y = 30 + 54x\)</span>가 가장 잘 들어맞는 선에 근사한다고 말했는데, 이때 “가장 잘 들어맞는다”는 것은 오차의 제곱합을 최소화하는 선(minimizing the sum of squared errors)이라는 것을 의미한다. 즉, 알고리즘에 따라 <span class="math inline">\(\sum^n_{i=1}(y_i - (a + bx_i))^2\)</span>를 최소화하는 <span class="math inline">\(a\)</span>와 <span class="math inline">\(b\)</span>의 값을 구하는 것이다. 한 번 R을 통ㅎ애 알아보자.</p>
<table>
<thead>
<tr>
<th style="text-align:right;">
id
</th>
<th style="text-align:right;">
daughter_height
</th>
<th style="text-align:right;">
mother_height
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
52.5
</td>
<td style="text-align:right;">
59.5
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
52.5
</td>
<td style="text-align:right;">
59.5
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
53.5
</td>
<td style="text-align:right;">
59.5
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
53.5
</td>
<td style="text-align:right;">
59.5
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
55.5
</td>
<td style="text-align:right;">
59.5
</td>
</tr>
</tbody>
</table>
<p>그러면 이제 어머니의 키로부터 딸의 키를 예측하는 회귀모델을 적합해보자. 데이터는 엄마-딸의 5524개 쌍의 키이며 모델은 세 개의 모수를 갖는다: 절편, 엄마 키에 대한 계수값, 그리고 잔차의 표준편차.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="background-on-regression-modeling.html#cb47-1" aria-hidden="true" tabindex="-1"></a>fit_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(daughter_height <span class="sc">~</span> mother_height, <span class="at">data=</span>heights)</span>
<span id="cb47-2"><a href="background-on-regression-modeling.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = daughter_height ~ mother_height, data = heights)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.7221 -1.4468  0.0981  1.5532  9.0981 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   29.79841    0.79034   37.70   &lt;2e-16 ***
## mother_height  0.54494    0.01264   43.12   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.262 on 5522 degrees of freedom
## Multiple R-squared:  0.2519, Adjusted R-squared:  0.2518 
## F-statistic:  1860 on 1 and 5522 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>데이터를 가지고 그래프를 한 번 그려보자. 1인치 단위로 산포도를 그리되, 각 변수를 확률변수로 만들 수 있다.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="background-on-regression-modeling.html#cb49-1" aria-hidden="true" tabindex="-1"></a>fig_1prac <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb49-2"><a href="background-on-regression-modeling.html#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">nrow</span>(heights),</span>
<span id="cb49-3"><a href="background-on-regression-modeling.html#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mother_height_jitt =</span> heights<span class="sc">$</span>mother_height <span class="sc">+</span> </span>
<span id="cb49-4"><a href="background-on-regression-modeling.html#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">runif</span>(n, <span class="sc">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span>),</span>
<span id="cb49-5"><a href="background-on-regression-modeling.html#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">daughter_height_jitt =</span> heights<span class="sc">$</span>daughter_height <span class="sc">+</span> </span>
<span id="cb49-6"><a href="background-on-regression-modeling.html#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">runif</span>(n, <span class="sc">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="regression-ghv_files/figure-html/unnamed-chunk-66-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>여기에다가 회귀모델에서 계수들을 추출해서 예측선을 플롯에 더해주면 된다.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="background-on-regression-modeling.html#cb50-1" aria-hidden="true" tabindex="-1"></a>a_hat <span class="ot">&lt;-</span> <span class="fu">coef</span>(fit_1)[<span class="dv">1</span>]</span>
<span id="cb50-2"><a href="background-on-regression-modeling.html#cb50-2" aria-hidden="true" tabindex="-1"></a>b_hat <span class="ot">&lt;-</span> <span class="fu">coef</span>(fit_1)[<span class="dv">2</span>]</span>
<span id="cb50-3"><a href="background-on-regression-modeling.html#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="background-on-regression-modeling.html#cb50-4" aria-hidden="true" tabindex="-1"></a>fig_1prac <span class="sc">%&gt;%</span> </span>
<span id="cb50-5"><a href="background-on-regression-modeling.html#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(mother_height_jitt, daughter_height_jitt)) <span class="sc">+</span> </span>
<span id="cb50-6"><a href="background-on-regression-modeling.html#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">1</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">alpha =</span> <span class="dv">2</span><span class="sc">/</span><span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb50-7"><a href="background-on-regression-modeling.html#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> a_hat, <span class="at">slope =</span> b_hat) <span class="sc">+</span> </span>
<span id="cb50-8"><a href="background-on-regression-modeling.html#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mother&#39;s height (inches)&quot;</span>,</span>
<span id="cb50-9"><a href="background-on-regression-modeling.html#cb50-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Adult daughter&#39;s height (inches)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb50-10"><a href="background-on-regression-modeling.html#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="regression-ghv_files/figure-html/unnamed-chunk-67-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>이 결과는 위의 Figure 6.2a와 동일하다.</p>
</div>
</div>
<div id="the-paradox-of-regression-to-the-mean" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> The paradox of regression to the mean</h2>
<p>그렇다면 과연 “키가 평균으로 회귀하는가?” Figure 5.2에서 나타나는 0.54라는 기울기는, 아니 사실 1보다 큰 모든 기울기는 사실 모순적으로 보인다. 만약 키가 큰 어머니가 키가 큰 딸을 가질 가능성이 크고, 키가 작은 어머니는 키가 작은 딸을 가질 가능성이 크다면, 딸들은 어머니들보다 평균에 수렴하고, 그러다보면 종래에는 모두 평균키가 된다는 이야기가 될 수 있다.</p>
<p>회귀모델의 함정이 이곳에 숨어잇다. 어머니의 키에 비해서 자녀의 예측된 키는 평균에 더 가까워지지만, 그것이 실제 키가 예측과 완벽하게 동일하다는 것을 의미하지는 않는다. 왜냐하면 현실 세계에서는 우리가 항상 모델에서 예측하지 못하는 “오차”가 존재하기 때문이다.</p>
<p>우리의 점추정치(점예측; 어떠한 한 점의 값으로 예측 한 것)은 평균으로 회귀하므로 그 계수값은 1보다 커질 수 있다. 그리고 점차 그 변동성(variation)은 감소한다(=평균과의 차이가 감소한다). 하지만 동시에 모델의 오차(예측의 불완전성)가 변동성을 더해 한 세대가 지나 다음 세대가 되더라도 키에 있어서 전체적인 변동성은 대략 일정해진다.</p>
<p>평균으로의 회귀는 안정적인 환경 하에서 예측이 불완전할 때라면 어떠한 형태로든 반드시 나타난다. 예측의 불완전성은 변동성을 초래하고, 전체적인 변동성을 일관되게 유지하기 위해 점추정치(예측)에 있어서의 회귀가 요구된다. 간단히 말하자면, 우리는 점점 평균키가 어느 정도인지에 대해서는 정확한 정보를 가지게 되지만 현실 세계 속에서 사람들의 키는 다양하게(오차를 가지고) 분포하기 때문에 전체적인 변동성-세대의 키는 한 세대가 지난다고 해서 모델처럼 뚜렷하게 변화하는 것이 아니다. 즉, 우리는 모델을 통해서 평균 키의 변화를 예측할 수 있지만, 그렇다고 해서 그것이 모든 관측치들-자녀들의 키가 다 평균으로 변해버린다는 것을 의미하지는 않는다.</p>
<div id="how-regression-to-the-mean-can-confuse-people-about-causal-inference-demonstration-using-fake-data" class="section level3" number="6.5.1">
<h3><span class="header-section-number">6.5.1</span> How regression to the mean can confuse people about causal inference; demonstration using fake data</h3>
<p>평균으로의 회귀라는 개념은 때로는 헷갈릴 수 있고, 종종 인과성으로 받아들여지는 오류를 야기한다. 이번에는 두 가지 종류의 시험을 치른 학생들에 대한 예제를 살펴보자.</p>
<p>Figure 6.4는 1,000명의 학생들의 중간고사와 기말고사 성적에 대한 가설적 데이터를 보여준다. 실제 데이터를 사용하기보다는 아래의 절차에 따라서 오차를 포함한 시뮬레이션된 시험 성적 데이터를 만들었다.</p>
<ol style="list-style-type: decimal">
<li><p>각 학생들은 평균 50, 표준편차 10이라는 분포에 실제 실력이 위치하고 있을 것으로 가정한다.</p></li>
<li><p>각 학생들의 중간고사 성적은 두 가지 요소의 합이다: 학생의 실제 실력과 평균 0, 표준편차가 10인 분포를 따르는 주어진 시험에 대한 성적에서 나타날 수 있는 예측불가능한 확률적 요소가 바로 그것이다. 중간고사는 완벽한 측정도구라고 보기는 힘들다. 예측이 불가능한 요소가 반영되어 있으니까.</p></li>
<li><p>마찬가지로 기말고사 점수도 실제 실력과, 그와는 독립적인 확률적 요소로 이루어져 있다.</p></li>
</ol>
<p>가설적인 시험 데이터를 한 번 만들어보자.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="background-on-regression-modeling.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2243</span>)</span>
<span id="cb51-2"><a href="background-on-regression-modeling.html#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="background-on-regression-modeling.html#cb51-3" aria-hidden="true" tabindex="-1"></a>n_sims <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb51-4"><a href="background-on-regression-modeling.html#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="background-on-regression-modeling.html#cb51-5" aria-hidden="true" tabindex="-1"></a>exams <span class="ot">&lt;-</span> </span>
<span id="cb51-6"><a href="background-on-regression-modeling.html#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb51-7"><a href="background-on-regression-modeling.html#cb51-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">true_ability =</span> <span class="fu">rnorm</span>(n_sims, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>),</span>
<span id="cb51-8"><a href="background-on-regression-modeling.html#cb51-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">noise_1 =</span> <span class="fu">rnorm</span>(n_sims, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">10</span>),</span>
<span id="cb51-9"><a href="background-on-regression-modeling.html#cb51-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">noise_2 =</span> <span class="fu">rnorm</span>(n_sims, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">10</span>),</span>
<span id="cb51-10"><a href="background-on-regression-modeling.html#cb51-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">midterm =</span> true_ability <span class="sc">+</span> noise_1,</span>
<span id="cb51-11"><a href="background-on-regression-modeling.html#cb51-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">final =</span> true_ability <span class="sc">+</span> noise_2</span>
<span id="cb51-12"><a href="background-on-regression-modeling.html#cb51-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>그리고 이제 데이터의 분포를 산포도를 통해 보여주고, 동시에 적합된 회귀선을 그려보자.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-69"></span>
<img src="regression-ghv_files/figure-html/unnamed-chunk-69-1.png" alt="Scatterplot of simulated midterm and final exam scores with fitted regression line, which has a slope of 0.45, implying that if a student performs well on the midterm, he or she is expected to do not so well on the final, and if a student performs poorly on the midterm, he or she is expected to improve on the final; thus, regression to the mean." width="672" />
<p class="caption">
Figure 6.4: Scatterplot of simulated midterm and final exam scores with fitted regression line, which has a slope of 0.45, implying that if a student performs well on the midterm, he or she is expected to do not so well on the final, and if a student performs poorly on the midterm, he or she is expected to improve on the final; thus, regression to the mean.
</p>
</div>
<p>회귀분석 결과는 다음과 같다.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="background-on-regression-modeling.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = final ~ midterm, data = exams)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -37.732   -7.733   -0.233    7.275   35.487  
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 24.82407    1.33986   18.53   &lt;2e-16 ***
## midterm      0.50864    0.02558   19.89   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 134.3792)
## 
##     Null deviance: 187250  on 999  degrees of freedom
## Residual deviance: 134110  on 998  degrees of freedom
## AIC: 7742.5
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<p>추정된 기울기는 약 0.5로 1보다 작다-평균으로의 회귀를 보여주는 결과이다. 중간고사에서 높은 점수를 받은 학생은 평균에 비해 약 절반 이상 높은 점수를 기말고사에 받는 경향이 나타났다. 중간고사에서 낮은 성적을 받은 학생은 기말고사에서도 평균보다 낮은 점수를 받는 경향이 나타났다.</p>
<ul>
<li>예를 들어, Figure 6.4에서 중간고사에서 0점을 받은 두 학생이 기말고사에서 각각 34, 42점을 받은 것을 확인할 수 있고, 반대로 중간고사에서 91점을받은 학생이 기말고사에서는 61점과 75점 사이를 받은 것을 확인할 수 있다.</li>
</ul>
<p>이 결과를 인과적으로 해석하는 것은 자연스러워 보인다. 즉, 중간고사에서 점수를 잘 받은 학생들이 더 실력이 좋지만 실력에 자만해서 기말고사에서는 썩 잘하지 못한다는 식으로 말이다. 한편, 이러한 인과적 추론에 따르면 중간고사에서 성적이 나빴던 학생이 더 열심히 해서 기말고사에서는 성적을 높였다라고 할 수도 있다.</p>
<p>그러나 사실 데이터는 어떠한 효과를 목적으로 하는 모델에서 시뮬레이션된 것은 아니다. 중간고사와 기말고사 모두 실제 실력에 무작위 잡음(random noise; 오차)이 반영되었을 뿐이다.</p>
<p>평균으로의 회귀라는 경향성은 첫 번째와 두 번째 관측치들 간의 변동성에 따른 결과이다: 중간고사에서 점수를 매우 잘 받은 학생이 운이 좋거나 실력이 더 좋을 가능성이 크다. 마찬가지로 중간고사에서 망한 애들이 기말고사에서 열심히 준비해 평균보다 더 나은 성적을 냈다는 것도 말이 된다.</p>
<p>이 문제에서 핵심은 Figure 6.4의 데이터에 대한 “순진한” 해석이 종종 허위적인(spurious) 효과를 추론하도록 연구자를 유인할 수 있다는 것이다. 이 경우는 “중간고사를 잘 본 친구는 기말고사에 나태해져서 성적이 더 잘 안나오고, 중간고사를 망친 학생은 더 열심히 공부해서 기말고사에 더 나아졌을 것이다”라는 진술로 이해할 수 있다. 이러한 오류를 “회귀의 오류(regression fallacy)”라고 한다.</p>
<p>실제 사례로는 심리학자 Amos Tversky와 Daniel Kahneman의 1973년 연구가 있다.</p>
<blockquote>
<p>항공학교에서 심리학자들의 조언에 따라 칭찬을 통해 성과를 제고하는 일종의 교육방침을 수립했는데, 강사들이 주장하기를 심리학자들이 이야기한 것과는 달리 칭찬해주니까 그 다음에 잘 못하더라는 것이었다.</p>
</blockquote>
<p>이에 대한 설명은 다음과 같다.</p>
<blockquote>
<p>항공 조작에 있어서 회귀란 필연적이다. 왜냐하면 조작 성과는 완벽하게 안정적이지 않고(reliable), 연이은 조작 간에 있어서 실력 향상은 더디기 때문이다. 따라서 한 번의 시도에 유독 좋은 성과를 낸 파일럿이 있다고 하더라도 다음 시도에서는 상대적으로 더 못할 가능성이 크다. 이는 첫 번째 성공에 대한 강사들의 반응(칭찬)에 무관하게 그러하다.<span class="math inline">\(\cdots\)</span> 보통 뭘 잘할 때 칭찬하고, 못할 때 처벌한다. 하지만 회귀의 관점에서 보자면 처벌받고 난 이후에 더 잘할 가능성이 있고, 보상을 받고 난 이후에 더 못할 수 있다. 결과적으로, 처벌에 대한 보상, 그리고 보상에 대한 처벌에 일생동안 노출되어 있는 것이다.</p>
</blockquote>
<p>이 이야기의 핵심은 예측에 대한 양적 이해(quantitative understanding)는 변동성(variation)과 인과성(causality)에 대한 근본적인 질적 혼동(qualitative confusion)을 명확하게 한다는 것이다.</p>
<ul>
<li><p>순수하게 수리적 관점에서 가장 조작을 잘 하는 파일럿은 실력이 다른 파일럿에 비하여 점점 떨어질 것이고, 가장 못하는 파일럿은 점차 잘 할 것이다.</p></li>
<li><p>마찬가지로 모든 키 큰 엄마로부터 나온 딸들은 평균적으로 엄마들만큼은 크지 않을 것이고 평균으로 수렴하게 될 것이다.</p></li>
</ul>
</div>
<div id="relation-of-regression-to-the-mean-to-the-larger-themes-of-the-book" class="section level3" number="6.5.2">
<h3><span class="header-section-number">6.5.2</span> Relation of “regression to the mean” to the larger themes of the book</h3>
<p>앞서 설명한 회귀의 오류는 비교에 대한 잘못된 해석의 한 사례라고 볼 수 있다. 인과추론에 있어 보다 핵심적인 것은, “같은 것끼리 비교해야 한다”는 것이다.</p>
<p>중간고사와 기말고사 성적에 관련된 예제를 다시 생각해보자. 인과적 주장은 “중간고사에서 잘 못한 학생이 동기부여가 되어서 기말고사에 더 열심히 준비한 반면, 중간고사에서 잘 한 학생은 안심하고 노는 바람에 기말고사를 망치고 말았을 것이다”라고 할 수 있다. 이 비교에서 종속변수인 <span class="math inline">\(y\)</span>는 기말고사 점수이고 예측변수 <span class="math inline">\(x\)</span>는 중간고사 점수이다. 문제는 <span class="math inline">\(x\)</span>에 있어서 한 단위가 변화한 학생을 비교할 때, <span class="math inline">\(y\)</span>에 있어서 <span class="math inline">\(frac{1}{2}\)</span>만큼의 차이를 기대할 수 있다는 것에 있다.</p>
<p>이 결과는 기울기가 1인 경우와 비교되었기 때문에 나타난 결과이다. 회귀분석 결과와 Figure 6.4에서 나타난 경험적 패턴은 암묵적인 디폴트 모델, 중간고사와 기말고사 성적이 모두 같다라고 보는 모델과 비교한 것이다. 그러나 기울기가 1인 모델과 0.5인 모델 간의 비교는 부적절하다. 왜냐하면 디폴트 모델 자체가 문제가 있기 때문이다. 우리는 중간고사 기말고사가 어떠한 의도적 개입이 존재하지 않았을 때, 완전히 동일할 것이라고 생각할 그 어떠한 근거도 가지고 있지 않기 때문이다.</p>
<p>결국 <span class="citation"><a href="#ref-ghv2020" role="doc-biblioref">Gelman, Hill, and Vehtari</a> (<a href="#ref-ghv2020" role="doc-biblioref">2020</a>)</span> 은 이 부분에서 회귀분석이 경험적 경향성에 대한 정보는 줄 수 있지만 인과적 관계를 담보해주지 않는다는, “Association does not mean causation”이라는 말을 굉장히 돌려돌려 여러가지 방식으로 다른 표현을 가지고 설명해주고 있다.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-ghv2020" class="csl-entry">
Gelman, Andrew, Jennifer Hill, and Aki Vehtari. 2020. <em>Regression and Other Stories</em>. Cambridge University Press.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="simulation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="simulation-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
